/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityLogsRouteImport } from './routes/app.activity-logs'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppBackupRouteImport } from './routes/app.backup'
import { Route as AppBookAppointmentRouteImport } from './routes/app.book-appointment'
import { Route as AppCampsRouteImport } from './routes/app.camps'
import { Route as AppConsultationRouteImport } from './routes/app.consultation'
import { Route as AppDoctorsRouteImport } from './routes/app.doctors'
import { Route as AppLabReportsRouteImport } from './routes/app.lab-reports'
import { Route as AppMedicalHistoryRouteImport } from './routes/app.medical-history'
import { Route as AppPatientRegistrationRouteImport } from './routes/app.patient-registration'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppPrescriptionsRouteImport } from './routes/app.prescriptions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppQrIdRouteImport } from './routes/app.qr-id'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppVolunteersRouteImport } from './routes/app.volunteers'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as RegisterAdminRouteImport } from './routes/register.admin'
import { Route as RegisterDoctorRouteImport } from './routes/register.doctor'
import { Route as RegisterPatientRouteImport } from './routes/register.patient'
import { Route as RegisterVolunteerRouteImport } from './routes/register.volunteer'
import { Route as AppPatientsIdRouteImport } from './routes/app.patients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLogsRoute = AppActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppBookAppointmentRoute = AppBookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => AppRoute,
} as any)
const AppCampsRoute = AppCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationRoute = AppConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppLabReportsRoute = AppLabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalHistoryRoute = AppMedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientRegistrationRoute = AppPatientRegistrationRouteImport.update({
  id: '/patient-registration',
  path: '/patient-registration',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppQrIdRoute = AppQrIdRouteImport.update({
  id: '/qr-id',
  path: '/qr-id',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVolunteersRoute = AppVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AppRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAdminRoute = RegisterAdminRouteImport.update({
  id: '/register/admin',
  path: '/register/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterDoctorRoute = RegisterDoctorRouteImport.update({
  id: '/register/doctor',
  path: '/register/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPatientRoute = RegisterPatientRouteImport.update({
  id: '/register/patient',
  path: '/register/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVolunteerRoute = RegisterVolunteerRouteImport.update({
  id: '/register/volunteer',
  path: '/register/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPatientsIdRoute = AppPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/activity-logs': typeof AppActivityLogsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/backup': typeof AppBackupRoute
  '/app/book-appointment': typeof AppBookAppointmentRoute
  '/app/camps': typeof AppCampsRoute
  '/app/consultation': typeof AppConsultationRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/lab-reports': typeof AppLabReportsRoute
  '/app/medical-history': typeof AppMedicalHistoryRoute
  '/app/patient-registration': typeof AppPatientRegistrationRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/qr-id': typeof AppQrIdRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/volunteers': typeof AppVolunteersRoute
  '/register/admin': typeof RegisterAdminRoute
  '/register/doctor': typeof RegisterDoctorRoute
  '/register/patient': typeof RegisterPatientRoute
  '/register/volunteer': typeof RegisterVolunteerRoute
  '/app/': typeof AppIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/activity-logs': typeof AppActivityLogsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/backup': typeof AppBackupRoute
  '/app/book-appointment': typeof AppBookAppointmentRoute
  '/app/camps': typeof AppCampsRoute
  '/app/consultation': typeof AppConsultationRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/lab-reports': typeof AppLabReportsRoute
  '/app/medical-history': typeof AppMedicalHistoryRoute
  '/app/patient-registration': typeof AppPatientRegistrationRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/qr-id': typeof AppQrIdRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/volunteers': typeof AppVolunteersRoute
  '/register/admin': typeof RegisterAdminRoute
  '/register/doctor': typeof RegisterDoctorRoute
  '/register/patient': typeof RegisterPatientRoute
  '/register/volunteer': typeof RegisterVolunteerRoute
  '/app': typeof AppIndexRoute
  '/register': typeof RegisterIndexRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/activity-logs': typeof AppActivityLogsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/backup': typeof AppBackupRoute
  '/app/book-appointment': typeof AppBookAppointmentRoute
  '/app/camps': typeof AppCampsRoute
  '/app/consultation': typeof AppConsultationRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/lab-reports': typeof AppLabReportsRoute
  '/app/medical-history': typeof AppMedicalHistoryRoute
  '/app/patient-registration': typeof AppPatientRegistrationRoute
  '/app/patients': typeof AppPatientsRouteWithChildren
  '/app/prescriptions': typeof AppPrescriptionsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/qr-id': typeof AppQrIdRoute
  '/app/queue': typeof AppQueueRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/users': typeof AppUsersRoute
  '/app/volunteers': typeof AppVolunteersRoute
  '/register/admin': typeof RegisterAdminRoute
  '/register/doctor': typeof RegisterDoctorRoute
  '/register/patient': typeof RegisterPatientRoute
  '/register/volunteer': typeof RegisterVolunteerRoute
  '/app/': typeof AppIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/patients/$id': typeof AppPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/activity-logs'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/attendance'
    | '/app/backup'
    | '/app/book-appointment'
    | '/app/camps'
    | '/app/consultation'
    | '/app/doctors'
    | '/app/lab-reports'
    | '/app/medical-history'
    | '/app/patient-registration'
    | '/app/patients'
    | '/app/prescriptions'
    | '/app/profile'
    | '/app/qr-id'
    | '/app/queue'
    | '/app/reports'
    | '/app/roles'
    | '/app/schedule'
    | '/app/settings'
    | '/app/users'
    | '/app/volunteers'
    | '/register/admin'
    | '/register/doctor'
    | '/register/patient'
    | '/register/volunteer'
    | '/app/'
    | '/register/'
    | '/app/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/activity-logs'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/attendance'
    | '/app/backup'
    | '/app/book-appointment'
    | '/app/camps'
    | '/app/consultation'
    | '/app/doctors'
    | '/app/lab-reports'
    | '/app/medical-history'
    | '/app/patient-registration'
    | '/app/patients'
    | '/app/prescriptions'
    | '/app/profile'
    | '/app/qr-id'
    | '/app/queue'
    | '/app/reports'
    | '/app/roles'
    | '/app/schedule'
    | '/app/settings'
    | '/app/users'
    | '/app/volunteers'
    | '/register/admin'
    | '/register/doctor'
    | '/register/patient'
    | '/register/volunteer'
    | '/app'
    | '/register'
    | '/app/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/activity-logs'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/attendance'
    | '/app/backup'
    | '/app/book-appointment'
    | '/app/camps'
    | '/app/consultation'
    | '/app/doctors'
    | '/app/lab-reports'
    | '/app/medical-history'
    | '/app/patient-registration'
    | '/app/patients'
    | '/app/prescriptions'
    | '/app/profile'
    | '/app/qr-id'
    | '/app/queue'
    | '/app/reports'
    | '/app/roles'
    | '/app/schedule'
    | '/app/settings'
    | '/app/users'
    | '/app/volunteers'
    | '/register/admin'
    | '/register/doctor'
    | '/register/patient'
    | '/register/volunteer'
    | '/app/'
    | '/register/'
    | '/app/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterAdminRoute: typeof RegisterAdminRoute
  RegisterDoctorRoute: typeof RegisterDoctorRoute
  RegisterPatientRoute: typeof RegisterPatientRoute
  RegisterVolunteerRoute: typeof RegisterVolunteerRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity-logs': {
      id: '/app/activity-logs'
      path: '/activity-logs'
      fullPath: '/app/activity-logs'
      preLoaderRoute: typeof AppActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backup': {
      id: '/app/backup'
      path: '/backup'
      fullPath: '/app/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book-appointment': {
      id: '/app/book-appointment'
      path: '/book-appointment'
      fullPath: '/app/book-appointment'
      preLoaderRoute: typeof AppBookAppointmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/camps': {
      id: '/app/camps'
      path: '/camps'
      fullPath: '/app/camps'
      preLoaderRoute: typeof AppCampsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultation': {
      id: '/app/consultation'
      path: '/consultation'
      fullPath: '/app/consultation'
      preLoaderRoute: typeof AppConsultationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doctors': {
      id: '/app/doctors'
      path: '/doctors'
      fullPath: '/app/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lab-reports': {
      id: '/app/lab-reports'
      path: '/lab-reports'
      fullPath: '/app/lab-reports'
      preLoaderRoute: typeof AppLabReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medical-history': {
      id: '/app/medical-history'
      path: '/medical-history'
      fullPath: '/app/medical-history'
      preLoaderRoute: typeof AppMedicalHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patient-registration': {
      id: '/app/patient-registration'
      path: '/patient-registration'
      fullPath: '/app/patient-registration'
      preLoaderRoute: typeof AppPatientRegistrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prescriptions': {
      id: '/app/prescriptions'
      path: '/prescriptions'
      fullPath: '/app/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qr-id': {
      id: '/app/qr-id'
      path: '/qr-id'
      fullPath: '/app/qr-id'
      preLoaderRoute: typeof AppQrIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/volunteers': {
      id: '/app/volunteers'
      path: '/volunteers'
      fullPath: '/app/volunteers'
      preLoaderRoute: typeof AppVolunteersRouteImport
      parentRoute: typeof AppRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/admin': {
      id: '/register/admin'
      path: '/register/admin'
      fullPath: '/register/admin'
      preLoaderRoute: typeof RegisterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/doctor': {
      id: '/register/doctor'
      path: '/register/doctor'
      fullPath: '/register/doctor'
      preLoaderRoute: typeof RegisterDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/patient': {
      id: '/register/patient'
      path: '/register/patient'
      fullPath: '/register/patient'
      preLoaderRoute: typeof RegisterPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/volunteer': {
      id: '/register/volunteer'
      path: '/register/volunteer'
      fullPath: '/register/volunteer'
      preLoaderRoute: typeof RegisterVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/patients/$id': {
      id: '/app/patients/$id'
      path: '/$id'
      fullPath: '/app/patients/$id'
      preLoaderRoute: typeof AppPatientsIdRouteImport
      parentRoute: typeof AppPatientsRoute
    }
  }
}

interface AppPatientsRouteChildren {
  AppPatientsIdRoute: typeof AppPatientsIdRoute
}

const AppPatientsRouteChildren: AppPatientsRouteChildren = {
  AppPatientsIdRoute: AppPatientsIdRoute,
}

const AppPatientsRouteWithChildren = AppPatientsRoute._addFileChildren(
  AppPatientsRouteChildren,
)

interface AppRouteChildren {
  AppActivityLogsRoute: typeof AppActivityLogsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBackupRoute: typeof AppBackupRoute
  AppBookAppointmentRoute: typeof AppBookAppointmentRoute
  AppCampsRoute: typeof AppCampsRoute
  AppConsultationRoute: typeof AppConsultationRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppLabReportsRoute: typeof AppLabReportsRoute
  AppMedicalHistoryRoute: typeof AppMedicalHistoryRoute
  AppPatientRegistrationRoute: typeof AppPatientRegistrationRoute
  AppPatientsRoute: typeof AppPatientsRouteWithChildren
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQrIdRoute: typeof AppQrIdRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVolunteersRoute: typeof AppVolunteersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityLogsRoute: AppActivityLogsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBackupRoute: AppBackupRoute,
  AppBookAppointmentRoute: AppBookAppointmentRoute,
  AppCampsRoute: AppCampsRoute,
  AppConsultationRoute: AppConsultationRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppLabReportsRoute: AppLabReportsRoute,
  AppMedicalHistoryRoute: AppMedicalHistoryRoute,
  AppPatientRegistrationRoute: AppPatientRegistrationRoute,
  AppPatientsRoute: AppPatientsRouteWithChildren,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQrIdRoute: AppQrIdRoute,
  AppQueueRoute: AppQueueRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVolunteersRoute: AppVolunteersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterAdminRoute: RegisterAdminRoute,
  RegisterDoctorRoute: RegisterDoctorRoute,
  RegisterPatientRoute: RegisterPatientRoute,
  RegisterVolunteerRoute: RegisterVolunteerRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
